---

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Check Docker & Docker Compose
      #   run: |
      #     docker --version
      #     docker compose version || echo "docker compose not available"
      #     docker-compose --version || echo "docker-compose not available"


      - name: Test
        run: docker compose run --rm app python manage.py test

      - name: Lint
        run: docker compose run --rm app flake8
